---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        exclude: ^tests/fixtures/.+?/templates/.+?\.yaml$
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^\.gitignore$
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.8.1
    hooks:
      - id: taplo
        args:
          - format
          - --option=reorder_arrays=true
          - --option=reorder_keys=true
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - Flake8-pyproject
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args:
          - -c
          - pyproject.toml
        additional_dependencies:
          - .[toml]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - .[toml]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt-src
        args:
          - --indent=4
          - --binary-next-line
          - --case-indent
          - --simplify
          - --write
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args:
          - --disable=MD013
  - repo: local
    hooks:
      - id: pylint
        name: Pylint
        entry: pylint
        args:
          - --enable-all-extensions
        language: system
        types:
          - python
      - id: mypy
        name: Mypy
        entry: mypy
        language: system
        types:
          - python
      - id: shellspec-syntax-check
        name: Syntax check of ShellSpec specfiles
        language: system
        entry: shellspec --no-kcov --syntax-check
