---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        exclude: ^tests/fixtures/.+?/templates/.+?\.yaml$
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^\.gitignore$
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping=2
          - --sequence=4
          - --offset=2
        exclude: ^tests/fixtures/.+?/templates/.+?\.yaml$
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.9.3
    hooks:
      - id: taplo-lint
      - id: taplo-format
        args:
          - --option=reorder_arrays=true
          - --option=reorder_keys=true
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-format
      - id: ruff-check
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt-src
        args:
          - --indent=4
          - --binary-next-line
          - --case-indent
          - --simplify
          - --write
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args:
          - --disable=MD013
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: mypy
        name: Mypy
        entry: mypy
        language: system
        types:
          - python
      - id: shellspec-syntax-check
        name: Syntax check of ShellSpec specfiles
        language: system
        entry: shellspec --no-kcov --syntax-check

ci:
  skip:
    - mypy
    - shellspec-syntax-check
    - taplo-lint
  autoupdate_commit_msg: 'chore(pre-commit): pre-commit autoupdate'
  autofix_commit_msg: 'fix(pre-commit): auto fixes from pre-commit.com hooks'
