---
name: Acceptance tests
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  acceptance-tests:
    name: Acceptance tests (${{ matrix.os }}, Helm ${{ matrix.helm_version }}, Python ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        helm_version:
          - '3.10.0'
          - '3.11.0'
          - '3.12.0'
          - '3.13.0'
          - '3.14.0'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v3
      - if: matrix.os == 'windows-latest'
        name: Install Cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: curl,unzip
      - name: Install Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Tox
        run: pip install tox
      - name: Install Helm ${{ matrix.helm_version }}
        uses: azure/setup-helm@v3.5
        with:
          version: ${{ matrix.helm_version }}
      - name: Install ShellSpec
        uses: ./.github/actions/shellspec
        with:
          shell: ${{ matrix.os == 'windows-latest' && 'sh -o igncr -e {0}' || 'sh' }}
      - name: Run acceptance tests
        run: tox -e py${{ matrix.python_version }} -e acceptance
