---
name: Linting
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Install ShellSpec
        uses: ./.github/actions/shellspec
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
