---
name: Unit tests
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  unit-tests:
    name: Unit tests (Python ${{ matrix.python_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Tox
        run: pip install tox
      - name: Install ShellSpec
        uses: ./.github/actions/shellspec
      - name: Install Kcov
        run: |
          sudo apt-get install -y kcov
      - name: Run unit tests
        run: tox -e py${{ matrix.python_version }}
      - if: matrix.python_version == '3.11'
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/shellspec/cobertura.xml,coverage/pytest/cobertura.xml
          fail_ci_if_error: true
